# Generated by Django 2.2.4 on 2019-08-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_file', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(default='*', max_length=20)),
                ('hour', models.CharField(default='*', max_length=20)),
                ('day_of_month', models.CharField(default='*', max_length=20)),
                ('month', models.CharField(default='*', max_length=20)),
                ('day_of_week', models.CharField(default='*', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.Command')),
            ],
        ),
    ]
