# Generated by Django 2.2.4 on 2019-08-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(default='*', max_length=20)),
                ('hour', models.CharField(default='*', max_length=20)),
                ('day_of_month', models.CharField(default='*', max_length=20)),
                ('month', models.CharField(default='*', max_length=20)),
                ('day_of_week', models.CharField(default='*', max_length=20)),
                ('script_path', models.CharField(default='TEST', max_length=100)),
            ],
        ),
    ]
